kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
---
kind: pipeline
type: docker
name: defaultX

steps:
- name: greetingX
  image: alpine
  commands:
  - echo hello
  - echo world
